# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ws < Formula
  desc "A simple CLI tool to quickly open VSCode Workspace"
  homepage "https://github.com/phe-lab/ws"
  version "1.2.0"

  on_macos do
    on_intel do
      url "https://github.com/phe-lab/ws/releases/download/v1.2.0/ws_1.2.0_darwin_amd64.tar.gz"
      sha256 "e73c810fa0ded943c6a77d44e526ef4d679ffddbdfc0bc4e55a6fa998e2effd8"

      def install
        bin.install "ws"
      end
    end
    on_arm do
      url "https://github.com/phe-lab/ws/releases/download/v1.2.0/ws_1.2.0_darwin_arm64.tar.gz"
      sha256 "4a0c3ea13f0392fd1b7fe479049c0073eb1212583e608267e8e412057b71377f"

      def install
        bin.install "ws"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/phe-lab/ws/releases/download/v1.2.0/ws_1.2.0_linux_amd64.tar.gz"
        sha256 "d900529e9a83420a341aac8150b2d74a11632c3138b2265095bdaaa67ab1acbb"

        def install
          bin.install "ws"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/phe-lab/ws/releases/download/v1.2.0/ws_1.2.0_linux_arm64.tar.gz"
        sha256 "c7c8940ecf86b7f09c3125d8896b85e022422336ec13c8f8c2c3b673ea43780d"

        def install
          bin.install "ws"
        end
      end
    end
  end

  test do
    assert_match /A simple CLI tool to quickly open VSCode Workspace/, shell_output("#{bin}/ws --help", 0)
  end
end
