# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ws < Formula
  desc "A simple CLI tool to quickly open VSCode Workspace"
  homepage "https://github.com/teguru-labs/ws"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/teguru-labs/ws/releases/download/v1.4.0/ws_1.4.0_darwin_amd64.tar.gz"
      sha256 "9bcc851ac30c469b9c537ff7fae87c0c5b94d851d8a2fe92b5df4f3c1d23d529"

      def install
        bin.install "ws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/teguru-labs/ws/releases/download/v1.4.0/ws_1.4.0_darwin_arm64.tar.gz"
      sha256 "0ff38e16d2bad72b09e5ada1898909f15edbdff79ae277a5386144ff9c7085aa"

      def install
        bin.install "ws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/teguru-labs/ws/releases/download/v1.4.0/ws_1.4.0_linux_amd64.tar.gz"
        sha256 "ee76c5dab14b9a069bbbb67b5f479388fed4ac2198498c3a7cc11050bdb90bd4"

        def install
          bin.install "ws"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/teguru-labs/ws/releases/download/v1.4.0/ws_1.4.0_linux_arm64.tar.gz"
        sha256 "b92f9f64070ca503777121d1ad6b2984daaaa6256bfc477f4ebfc5eaaff20f61"

        def install
          bin.install "ws"
        end
      end
    end
  end

  test do
    assert_match /A simple CLI tool to quickly open VSCode Workspace/, shell_output("#{bin}/ws --help", 0)
  end
end
